[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
tauri = { version = "2.5.1", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2.0.12"
log = "0.4.27"
