[package]
name = "settings"
version = "0.0.0"
edition = "2024"

[dependencies]
tauri = { version = "2" , features = [] }
tauri-plugin-store = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
zeromq = "0.4.1"
thiserror = "2.0.12"
log = "0.4.27"
