[package]
name = "sidecars"
version = "0.0.0"
edition = "2024"
links = "sidecars"

[dependencies]
tauri = { version = "2", default-features = false }
tauri-plugin-shell = "2"
log = "0.4"

zeromq = "0.4.1"

[build-dependencies]
tauri-plugin= { version = "2", features = ["build"] }
