[package]
name = "async_bevy"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.16", default-features = false, features = ["multi_threaded", "std"] }
tokio = { version = "1", features = ["full"] }
async-nats = "0.42"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
futures = "0.3"
thiserror = "2"
reqwest = { version = "0.12", features = ["json", "stream", "multipart"] }
